SELECT 
to_char(ALARM_TIME,'yyyy-mm-dd hh24:mi')  alarm_time
,regexp_substr(substr(DN,17,7),'[0-9]+') lnbtsid
--,substr(obj.co_name,1,6)  city
--,obj.co_name  ENB_name
--,OBJ.CO_OBJECT_INSTANCE AS OBJ_ID
,cipno.ipno_mpia_8 ip
,DECODE(OBJ.CO_OC_ID,100,'OMC',2237,'MRBTS',2255,'LNBTS',2270,'LNCEL',2259,'FTM',OBJ.CO_OC_ID) AS OBJ_NAME
,ALARM_NUMBER  "???"
,SUPPLEMENTARY_INFO
,DIAGNOSTIC_INFO
,TEXT
--,NE_OBJ.CO_NAME AS BTS_NAME
--,DN
,ALARM_TYPE
,SEVERITY
,ALARM_STATUS

,CANCEL_TIME
,DURATION_HOUR


FROM
(
SELECT
NE_GID
,DN
,DECODE(ALARM_TYPE,1,'COMM',2,'ENVIR',3,'EQUIP',4,'PROC',5,'QUAL',ALARM_TYPE) ALARM_TYPE
,DECODE(SEVERITY,1,'CRITICAL',2,'MAJOR',3,'MINOR',4,'WARNING',SEVERITY) SEVERITY
,DECODE(ALARM_STATUS,0,'CANCELED',1,'ACTIVE',ALARM_STATUS) ALARM_STATUS
,ALARM_TIME AS ALARM_TIME
,to_char(CANCEL_TIME,'yyyymmdd hh24:mi') AS CANCEL_TIME
,ROUND(DECODE(CANCEL_TIME,NULL,DECODE(ALARM_STATUS,0,UPDATE_TIMESTAMP+8/24-ALARM_TIME,SYSDATE-ALARM_TIME),CANCEL_TIME-ALARM_TIME)*24,2) AS DURATION_HOUR
,ALARM_NUMBER
,TEXT
,SUPPLEMENTARY_INFO
,DIAGNOSTIC_INFO

FROM
FX_ALARM

-- WHERE  ALARM_STATUS=1
ORDER BY ALARM_TIME DESC
) A
,CTP_COMMON_OBJECTS OBJ,CTP_COMMON_OBJECTS NE_OBJ,c_lte_ipno cipno
WHERE 
A.NE_GID=OBJ.CO_GID(+)
AND A.NE_GID=NE_OBJ.CO_GID(+)
--and ALARM_NUMBER in (71058)  
--AND ALARM_TIME > =to_date(&stime,'yyyymmddHH24MI') 

and to_char(ALARM_TIME,'yyyymmddHH24MI') > &1
--and to_char(a.ALARM_TIME,'yyyymmddHH24MI') < &2

--and SUPPLEMENTARY_INFO not like '%X2%'
AND ALARM_NUMBER  NOT IN (9252)
--and SUPPLEMENTARY_INFO  like '%S1%'  

and (SUPPLEMENTARY_INFO like 'BTS Master Clock tuning failure' or SUPPLEMENTARY_INFO like 'Bts autonomous reset as recovery action')
--and (SUPPLEMENTARY_INFO like 'BTS Master Clock tuning failure')

and regexp_substr(substr(DN,17,7),'[0-9]+') = cipno.ipno_bts_id(+)
--AND NE_OBJ.CO_OC_ID IN (2255,2263)
--and regexp_substr(substr(DN,17,7),'[0-9]+') in (&ENB)
--&2&3&4